name: build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 8 for build
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          server-id: github
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble app
        run: ./gradlew :app:assembleDebug $commonGradleFlags

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk